name: Survey Image CI/CD
on: push

# Global variables
env:
  IMAGE_NAME: "survey_distro:latest"

# Jobs
jobs:
  CI_CD:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    # Clone the repo
      - name: Check Out Repo 
        uses: actions/checkout@v2

    # Build the image 
      - name: Build
        run: |
        echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME" > docker.env
        cat docker.env
        docker-compose --env-file=docker.env build && docker images

    # Login to GitHub's container registry
      - name: Login
        run: echo $GITHUB_TOKEN | docker login -u $USER_NAME --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          USER_NAME: ${{github.actor}}

    # Push the image to the registry
      - name: Push
        run: docker-compose push



