name: Survey Image CI/CD
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Build
        run: docker-compose build && docker images

      - name: Push
        run: echo $GITHUB_TOKEN | docker login -u $USER_NAME --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          USER_NAME: ${{github.actor}}



