name: Survey Image CI/CD
on: push

# Global variables
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  USER_NAME: ${{github.actor}}
  GITHUB_SHA: ${{github.sha}}

# Jobs
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    # Clone the repo
      - name: Check Out Repo 
        uses: actions/checkout@v2

    # Build the image 
      - name: Build
        run: |
          VERSION=$(echo "${SHA:0:6}")
          echo $VERSION
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/survey_distro:$VERSION" > docker.env
          docker-compose --env-file=docker.env build && docker images

    # Login to GitHub's container registry
      - name: Login
        run: echo $GITHUB_TOKEN | docker login -u $USER_NAME --password-stdin ghcr.io

    # Push the image to the registry
      - name: Push
        run: docker-compose --env-file=docker.env push


# jobs:
  CD:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    # Clone the repo
      - name: Check Out Repo 
        uses: actions/checkout@v2

    # Build the image 
      - name: Deploy
        run: |
          VERSION=$(echo "${SHA:0:6}")
          echo $VERSION
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/survey_distro:$VERSION" > docker.env
          docker-compose --env-file=docker.env build && docker images

    # Login to GitHub's container registry
      - name: Login
        run: echo $GITHUB_TOKEN | docker login -u $USER_NAME --password-stdin ghcr.io

    # Push the image to the registry
      - name: Push
        run: docker-compose --env-file=docker.env push
